name: install
description: 'Set yarn version and install'

runs:
  using: composite
  steps:
    - name: yarn install
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: corepack prepare yarn@3.5.0 --activate
      shell: bash
    - run: yarn set version 3.5.0
      shell: bash
    - name: yarn install (cache)
      uses: ./.github/actions/yarn-nm-install
      with:
        enable-corepack: false
        cache-install-state: true
        cache-node-modules: true
